experiment:
  github_version: v1.0
  save_dir: /mnt/data2/zzixuantang/MICCAI2MedIA/exp
  experiment_name: "baseline"


data:
  data_root: '/mnt/data2/zzixuantang/classfier_convNext/data/00-HAM10000'
  label_path: '/mnt/data2/zzixuantang/classfier_convNext/data/00-HAM10000/label'
  train_img_path: '/mnt/data2/zzixuantang/classfier_convNext/data/00-HAM10000/train'
  train_text_desc_path: '/home/ub/tzx/MICCAI2MedIA/image_descriptions.json'
  test_img_path: '/mnt/data2/zzixuantang/classfier_convNext/data/00-HAM10000/test'
  test_text_desc_path: '/home/ub/tzx/MICCAI2MedIA/image_descriptions_test.json'

train:
  epoch: 20
  log_every_n_steps: 10
  check_val_every_n_epoch: 1
  save_topk: 3
  learning_rate: 0.00001
  batch_size: 16
  num_workers: 0

model:
  baseline:
    mamba_fusion: 
      num_layer: 1
      indims: [768, 512]
      outdims: [512, 256]
      indims_fusion: [256, 512]
      outdims_fusion: [512, 768]
      dim_model: 128